steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://agrovision-be/.env", ".env"]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/agrovision:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-nodejs-app']
    args: ['push', 'gcr.io/$PROJECT_ID/agrovision:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'agrovision', '--image', 'gcr.io/$PROJECT_ID/agrovision:$SHORT_SHA', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/agrovision:$SHORT_SHA'
